### ISSUE TITLE
Dell ST2010

### ISSUE THREAD

**Issue by tianheg** [tianheg/ideas#61]
买了个老爷显示器，大概是 2010 年前后生产的。

显示屏尺寸 | 20英寸
-- | --
屏幕比例 | 16:9
可视角度 | 160/160°
面板类型 | TN
亮度 | 250cd/㎡
对比度 | 1000:1
黑白响应时间 | 5ms
最佳分辨率 | 1600×900
接口类型 | D-Sub,HDMI
消耗功率 | 20W

**Comment by Gaotianhe** [comment]
## 液晶显示器的最长寿命是多久

液晶显示器以机身薄，节省空间；省电，不产生高温；低辐射，益健康；画面柔和不伤眼等优点现在被大家所广泛利用，那大家对液晶显示器的寿命是多久有没有了解呢，下面小编就来介绍一下液晶显示器的寿命是多久，希望对大家有所帮助。

液晶显示器的寿命是多久？

1、大约50000小时，主要是根据亮度下降为出厂值规格的一半定义寿命的。

2、其他因素

（1）背光源的CCFL（冷阴极灯管）容易出现老化、漏气、破碎等等不良。

（2）屏驱动电路由于电器元件容易出现电性不良，如IC、电容等。

（3）显示屏由于静电、异物等容易出现亮暗点、线等缺陷。

3、灯管的老化主要是根据亮度和颜色来区分，老化的亮度会降低，白光的颜色偏黄色。液晶屏的老化通常不易分辨，严重的会有亮暗点或线缺陷的出现。

4、液晶屏会老化的，因为里面也有半导体元件，而且液晶也会老化。

5、两者是分离的，但一定不要自己维修，因为屏与背光的组装和拆解是在无尘室和抗静电环境下进行的，普通环境是不行的，而且灯管的更换要将背光也拆掉，没有拆过的可能会造成光学材料的损坏。可以找厂商修理，只换灯管不是很贵，但如果里面的光学材料弄坏了可就比较贵了。

其他知识：

一、液晶显示器的寿命

液晶显示器功耗小无辐射，对于长期使用电脑的工作者来说，液晶显示器是十分适合的。不足的是，液晶显示器的寿命相当短，现在市面上绝大多数的液晶显示器的标称使用寿命均为2～3万小时(据说优派液晶显示器能达到5～6万小时)。也就是说，如果一天24小时开机，只可以使用833～1250天，只有不到3.5年的时间，而且在使用过程中，亮度会逐渐减弱。和液晶显示器相比，CRT显示器寿命一般都达10年之长，而且显示效果也不会受太大的影响。不过，对IT产品来说，能使用5年已经不错了，也该更新换代了。

液晶显示器的核心部件是液晶层与上下的两片偏振片以及背光组件，背光组件的主要部件是背光灯管和导光板两个部分，决定寿命的主要是背光灯管的寿命，在达到一定时间期限后，背光灯管会出现老化，亮度随之降低，当灯管亮度衰减到50%时的使用时间即定义为灯管寿命。

液晶显示器亮度减低到一定时候，会出现不太明显的扫描线，这是因为显示器自动降低了灯管的频率的缘故。

二、液晶显示器的分辨率

分辨率是指单位面积显示像素的数量。液晶面板就好象排列好的一个个小门，用来让光通过，液晶屏所能表现的像素便是由单位面积上的“小门”的数量来决定的，这就决定了液晶显示器的物理分辨率是固定不变的。而普通CRT显示器，只要调整电子束的偏转电压，就可以改变不同的分辨率。

不论是LCD液晶显示器或一般的CRT显示器，分辨率是主要的参数。显示器一定要能支持应用软硬件所需的分辨率，但LCD只支持所谓的真实分辨率，可比喻为一般CRT显示器的最高分辨率，只有在真实分辨率下才能显现最佳影像。

LCD显示器呈现分辨率较低的显示模式时的两种显现方式：第一种为居中显示。整个画面看起来好像是影像居中缩小，走出显示像素的外围由阴影环绕；第二种为扩展显示。虽没有阴影边缘环绕，但清晰度会受到影响。所以选择液晶显示器时，在确保能支持所使用的应用软硬件的原始分辨率下，并不是分辨率要越高越好。作为一般用户来说，能支持1024*768足矣。

三、分辨率与液晶显示器寿命关系

普通17寸液晶显示器的默认分辨率是1280*1024，如用于1024*768(算法模拟的分辨率)，除影响清晰度外，对寿命没有影响。

四、使用液晶显示器注意事项

1、建议在常温/常湿环境下工作，高温/高湿会影响液晶显示器的寿命。

2、激烈的温度波动会影响液晶显示器的性能，特别是低温会影响亮度和响应时间。建议在平稳、干净的环境下工作，灰尘会引起内部电路失效。

3、不要让液体溅入显示器内部，如需清洁请关闭电源，将清洁剂喷射在软布上再轻轻擦拭。4、液晶显示器是玻璃制品，搬动时应避免碰撞、震动。

5、液晶显示器表面有多层薄膜，严禁用锐器刻划。

6、严禁随意拆卸液晶显示器，如遇故障务必请专业人员维修。

7、长时间显示固定画面，会使亮度下降、图像滞留现象加大，建议使用屏幕保护程序。

8、长时间不用请关闭显示器电源，拔掉电源插头。

来源：http://scitech.people.com.cn/n1/2016/0525/c404214-28378466.html
