### ISSUE TITLE
中国食辣史

### ISSUE THREAD

**Issue by tianheg** [tianheg/ideas#73]
【一席】曹雨：中国食辣史

**Comment by Gaotianhe** [comment]
中国的饭和菜，是不同系统的东西

**Comment by Gaotianhe** [comment]
明清时期，粮食产量达到瓶颈，人口却在不断增加。“严重的内卷化”

**Comment by Gaotianhe** [comment]
食辣=驱寒避湿？

> 人是悬挂在自我编织的意义之网上的动物。

**Comment by Gaotianhe** [comment]
为什么移民【从一个没有吃辣传统的地方来到像北京，上海这种大城市，在这些地方他们吃辣】吃辣？
