### ISSUE TITLE
一条被子——我的心路历程

### ISSUE THREAD

**Issue by tianheg** [tianheg/ideas#74]
我看着那条被子，它安静地躺在地上。我想它怎么掉到地上了，或许是风刮的，今天有风。

我站在一楼寝室的阳台上，注视着那条被子，往来的人很多，很多，但是，没有把被子捡起的人。

我跟室友说，“有很多人路过被子，但是没有人把它捡起来。”“你为什么不去捡呢？”室友问。“我不想去。”我回答说。

为什么呢？因为我现在很在意做一件事的后果。以前的我不是这样，别人需要帮助时，我会伸出援手，没有多余的想法，就是非常纯粹地想帮助一个人。

现在呢？我会想到很多，我会想一想利害关系，我开始迟疑，是否选择帮助别人。

室友问我：“当你路过那条被子时，你会捡起来吗？”我回答不会，因为我考虑到了后果，我在意别人怎样看待我。但是，当我事后反思时，我就觉得自己应该把它捡起来。

因为最近我学到的一个词语——换位思考。如果，我是那个被子晒在外面的人，想到自己的被子掉在地上，我会怎么想。我一定想着说：我是希望有人能把它捡起来的。因为地面是潮湿的，放在地上的被子进潮了盖起来很不舒服。

最后，我去做了，我把被子捡了起来。我能够做到这件事，一是因为此前的各种分析，最后换位思考帮我做了决定，二是在捡起这条被子之前，我还捡了两次在宿舍里看不到位置的被子。可以说，这两次行动给了我继续的勇气。

**Comment by Gaotianhe** [comment]
也可能有一个问题：因为我捡了被子，它的主人不知道被子曾经在地上呆过，会误以为被子已经晒好了。
