### ISSUE TITLE
但丁《神曲》

### ISSUE THREAD

**Issue by tianheg** [tianheg/ideas#84]
来源微信读书关于《神曲》的注解：

> 听人琐碎的谈话或相骂，是人类的低级趣味，高尚人不屑做的；但丁被维吉尔（智慧的象征）提醒，马上就悔悟了，有“前事如梦”的感觉，“后不再犯”的决心。

**Comment by Gaotianhe** [comment]
来源微信读书《神曲》中关于“库拉多·玛拉斯庇那”的注解
> 库拉多·玛拉斯庇那（Currado Malaspina）为卢尼地区（Lunigiana）之侯爵。老库拉多死于一二五五年，小库拉多（库拉多第二，库拉多第一之孙）死于一二九四年，即此处发言之灵魂。小库拉多自谓太爱家族，即努力家族之发展，而疏忽其精神上之修养（尤指信仰方面），此乃疏忽的灵魂之通病也。库拉多第二有堂兄弟二人，其一为牟洛埃罗（Moroello Ⅲ），见《地狱》第二十四篇注11；其二见下注。

**Comment by Gaotianhe** [comment]
> 哦，太阳呀！他把我昏暗的精神照明亮了；从一个疑问得着一段知识，你使我多么快活呀！

**Comment by Gaotianhe** [comment]
> 七情六欲，人所不能免，但任性乖戾，太过与不及，均非正道，而为罪恶之源。此处“爱”字（意文amor，法文amour，英文love）之意义，实相当于“情欲”二字。
