### ISSUE TITLE
色欲对人的影响

### ISSUE THREAD

**Issue by tianheg** [tianheg/ideas#86]
色欲存在的必要及其原因，有待我的学习与探索

**Comment by Gaotianhe** [comment]
放纵色欲滋长，会让人失去理智，行为趋向野兽。

**Comment by Gaotianhe** [comment]
在看小黄片时，大脑的某处会特别兴奋，但是持续看、过量看，该处的兴奋会变成经常性兴奋。会影响正常生活。

**Comment by Gaotianhe** [comment]
## 我的黄片史

**Comment by Gaotianhe** [comment]
看完黄片后会产生强烈的后悔感。对自己看黄片痛恨，但又垂涎于看片时的刺激，欲罢不能。

**Comment by Gaotianhe** [comment]
对腰部的器官也有影响
