### ISSUE TITLE
要回学校了，父母亲让我回去看望舅舅和爷爷

### ISSUE THREAD

**Issue by tianheg** [tianheg/ideas#9]
要返校，父亲说回去看看爷爷吧，母亲则说去看看姥姥吧。
我不想去。我拒绝了。我觉得实在没有必要，因为我不知道自己把他们（舅舅和爷爷）摆在什么样的位置。
我在一心摆弄着自己的事情。我脑子很乱，实在装不下这么多事情。
父亲说，你不去。别人不会说你，而是说你的父母（也就是我）没有教养，不会教小孩。
可是，不去就代表不爱吗，没有人敢肯定。为什么一定要去呢？
如果这是一个习俗的话，我大概率是摒弃的。这是我当下的想法，因为有比这更加重要的事情等着我去做。

**Comment by Gaotianhe** [comment]
一种迷惘，我在完成父母对于我的期待

**Comment by Gaotianhe** [comment]
我去舅舅家了，也将去看望爷爷。这是一种怎样的感觉？看到亲戚，看到许久不见的人，我和他们应该处于怎样的关系

**Comment by Gaotianhe** [comment]
什么是亲情？
